# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NIGHT',
            fields=[
                ('calibration_night', models.DateTimeField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Night of calibration')),
                ('all_rawcal', models.BooleanField(default=False, editable=False, verbose_name='All raw calibration frames present')),
                ('masterbias', models.BooleanField(default=False, editable=False, verbose_name='Master bias present')),
                ('masterflat', models.BooleanField(default=False, editable=False, verbose_name='Master flat present')),
                ('wavesol_flag', models.BooleanField(default=False, editable=False, verbose_name='Wavelength solution present')),
            ],
        ),
        migrations.CreateModel(
            name='OBJECT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(editable=False, max_length=100, verbose_name='Object name')),
                ('V_mag', models.FloatField(blank=True, editable=False, null=True, verbose_name='V mag.')),
                ('ra', models.FloatField(editable=False, verbose_name='RA')),
                ('dec', models.FloatField(editable=False, verbose_name='DEC')),
                ('is_RVstd', models.BooleanField(default=False, editable=False, verbose_name='Target is RV standard star')),
                ('CCF_plot', models.FilePathField(editable=False, max_length=250, verbose_name='Path to the CCF')),
            ],
        ),
        migrations.CreateModel(
            name='OBSMODE',
            fields=[
                ('name', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Obsmode')),
                ('clock_speed', models.CharField(editable=False, max_length=500, verbose_name='Detector clock speed')),
                ('cdelt1', models.IntegerField(editable=False, verbose_name='CDELT1')),
                ('cdelt2', models.IntegerField(editable=False, verbose_name='CDELT2')),
                ('gain', models.FloatField(editable=False, verbose_name='Gain')),
                ('readout_noise', models.FloatField(editable=False, verbose_name='Readout noise')),
                ('readout_time', models.FloatField(editable=False, verbose_name='Readout time')),
            ],
        ),
        migrations.CreateModel(
            name='RAW_IMAGE',
            fields=[
                ('imagename', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='Image name')),
                ('path', models.FilePathField(editable=False, max_length=250, verbose_name='Fits file path')),
                ('exptime', models.FloatField(default=0.0, editable=False, verbose_name='Exposure time')),
                ('obstime', models.DateTimeField(editable=False, null=True, verbose_name='Obs. date & time')),
                ('binning', models.CharField(editable=False, max_length=3, verbose_name='Binning')),
                ('imtype', models.CharField(editable=False, max_length=4, verbose_name='Image type [bias, flat, wave, lamp, ThAr, object-cal, undefined]')),
            ],
        ),
        migrations.CreateModel(
            name='RED_SPECTRUM',
            fields=[
                ('imagename', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='Image name')),
                ('path', models.FilePathField(editable=False, max_length=250, verbose_name='Fits file path')),
            ],
        ),
        migrations.CreateModel(
            name='RVs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateobs', models.FloatField(verbose_name='Obs. date [BJD]')),
                ('mes_RV', models.FloatField(verbose_name='meas. RV')),
                ('mes_RV_err', models.FloatField(verbose_name='meas. RV err.')),
                ('bisector', models.FloatField(blank=True, null=True, verbose_name='bisector span')),
                ('bisector_err', models.FloatField(blank=True, null=True, verbose_name='error bisector span')),
                ('Teff', models.FloatField(blank=True, null=True, verbose_name='effective temperature')),
                ('logg', models.FloatField(blank=True, null=True, verbose_name='log(g)')),
                ('feh', models.FloatField(blank=True, null=True, verbose_name='[Fe/H]')),
                ('vsini', models.FloatField(blank=True, null=True, verbose_name='v sin i')),
                ('peak', models.FloatField(blank=True, null=True, verbose_name='lowest point CCF')),
                ('stdCCF', models.FloatField(blank=True, null=True, verbose_name='standard deviation CCF')),
                ('snr', models.FloatField(blank=True, null=True, verbose_name='SNR at ~5150 Angstrom')),
                ('exptime', models.FloatField(blank=True, null=True, verbose_name='Exp. time')),
                ('target_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FEROS.OBJECT')),
            ],
            options={
                'ordering': ['dateobs'],
            },
        ),
        migrations.CreateModel(
            name='WAVESOL',
            fields=[
                ('imagename', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='Image name')),
                ('path', models.FilePathField(editable=False, max_length=250, verbose_name='Pickle file path')),
                ('rms', models.FloatField(default=0.0, editable=False, verbose_name='Final RMS')),
                ('obstime', models.DateTimeField(editable=False, null=True, verbose_name='Obs. date & time')),
                ('N_l', models.FloatField(default=0.0, editable=False, verbose_name='Number of lines')),
                ('precision', models.FloatField(default=0.0, editable=False, verbose_name='Achievable precision')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FEROS.NIGHT')),
            ],
        ),
        migrations.CreateModel(
            name='RAW_BIAS',
            fields=[
                ('raw_image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FEROS.RAW_IMAGE')),
                ('counts', models.FloatField(default=0.0, editable=False, verbose_name='Counts')),
            ],
            bases=('FEROS.raw_image',),
        ),
        migrations.CreateModel(
            name='RAW_FLAT',
            fields=[
                ('raw_image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FEROS.RAW_IMAGE')),
                ('counts1', models.FloatField(default=0.0, editable=False, verbose_name='Counts fibre 1')),
                ('counts2', models.FloatField(default=0.0, editable=False, verbose_name='Counts fibre 2')),
            ],
            bases=('FEROS.raw_image',),
        ),
        migrations.CreateModel(
            name='RAW_LAMP',
            fields=[
                ('raw_image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FEROS.RAW_IMAGE')),
                ('counts1', models.FloatField(default=0.0, editable=False, verbose_name='Counts fibre 1')),
                ('counts2', models.FloatField(default=0.0, editable=False, verbose_name='Counts fibre 2')),
            ],
            bases=('FEROS.raw_image',),
        ),
        migrations.AddField(
            model_name='red_spectrum',
            name='raw_spectra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FEROS.RAW_IMAGE'),
        ),
        migrations.AddField(
            model_name='red_spectrum',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FEROS.NIGHT'),
        ),
        migrations.AddField(
            model_name='raw_image',
            name='obsmode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FEROS.OBSMODE'),
        ),
        migrations.AddField(
            model_name='raw_image',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FEROS.NIGHT'),
        ),
        migrations.AddField(
            model_name='object',
            name='raw_spectra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FEROS.RAW_IMAGE'),
        ),
        migrations.AddField(
            model_name='object',
            name='red_spectra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FEROS.RED_SPECTRUM'),
        ),
    ]
