# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEROS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_image',
            name='obsmode',
        ),
        migrations.DeleteModel(
            name='OBSMODE',
        ),
    ]
